<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>library</OutputType>
        <TargetFramework>${CSHARP_LIBRARY_VERSION}</TargetFramework>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <AssemblyVersion>${GDAL_VERSION_MAJOR}.${GDAL_VERSION_MINOR}.${GDAL_VERSION_REV}</AssemblyVersion>
        <AssemblyOriginatorKeyFile>..\gdal.snk</AssemblyOriginatorKeyFile>
        <SignAssembly>true</SignAssembly>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageId>${_PACKAGE_NAME}</PackageId>
        <Authors>GDAL Contributors</Authors>
        <Company>Hexagon AB and/or its subsidiaries and affiliates</Company>
        <Product>GDAL C# Library</Product>        
        <Copyright>(c) 1999-2027 Hexagon AB and/or its subsidiaries and affiliates</Copyright>
    </PropertyGroup>
    <ItemGroup>
        <None Include="$<TARGET_FILE:${_CSHARP_WRAP_DLL}>" Pack="true" PackagePath="runtimes\${CSHARP_RID}\native" />
    </ItemGroup>
</Project>
